### ISSUE TITLE
IndexError responding to !topic in a channel with no topic set

### ISSUE THREAD

**Issue by alanbriolat** [HackSoc/csbot#178]
As the title says, the `!topic` command in a channel with no topic causes the following exception:

```
Traceback (most recent call last):
  File "/app/src/csbot/events.py", line 255, in _finish_async_handler
    await future
  File "/app/src/csbot/core.py", line 172, in fire_command
    await maybe_future_result(f(event), log=self.log)
  File "/app/src/csbot/plugin.py", line 56, in __call__
    return getattr(self.obj, self.name)(*args, **kwargs)
  File "/app/src/csbot/plugins/topic.py", line 89, in topic
    topic = self._get_topic(e['channel'])
  File "/app/src/csbot/plugins/topic.py", line 71, in _get_topic
    return self.topics[channel][-1]
IndexError: deque index out of range
```

**Comment by alanbriolat** [comment]
Duplicate of #157.
