### ISSUE TITLE
"'Collection' object is not callable" in `last` plugin (due to pymongo update?)

### ISSUE THREAD

**Issue by alanbriolat** [HackSoc/csbot#182]
```
bot_1         | Traceback (most recent call last):
bot_1         |   File "/app/src/csbot/events.py", line 239, in _run_handler
bot_1         |     result = handler(event)
bot_1         |   File "/app/src/csbot/plugins/last.py", line 107, in _apply_update
bot_1         |     self.db.remove(e['query'])
bot_1         |   File "/usr/local/lib/python3.9/site-packages/pymongo/collection.py", line 2584, in __call__
bot_1         |     raise TypeError("'Collection' object is not callable. If you meant to "
bot_1         | TypeError: 'Collection' object is not callable. If you meant to call the 'remove' method on a 'Collection' object it is failing because no such method exists.
```

**Comment by alanbriolat** [comment]
Fixed by #184.
