### ISSUE TITLE
Autoreconnect on connection failure

### ISSUE THREAD

**Issue by LordAro** [HackSoc/csbot#96]
It would be nice if csbot had the option to keep trying to reconnect, on connection failure

```
[2015/04/26 07:49:51] (E:asyncio) Fatal read error on socket transport
protocol: <csbot.core.BotClient object at 0x8081bf400>
transport: <asyncio.selector_events._SelectorSocketTransport object at 0x8081bfac8>
Traceback (most recent call last):
  File "/home/urybot/.pyenv/versions/3.4.1/lib/python3.4/asyncio/selector_events.py", line 466, in _read_ready
    data = self._sock.recv(self.max_size)
TimeoutError: [Errno 60] Operation timed out
[2015/04/26 07:49:52] (I:csbot.pretty_log) [Disconnected: TimeoutError(60, 'Operation timed out')]
[2015/04/26 07:50:17] (E:asyncio) Future/Task exception was never retrieved
future: Task(<create_connection>)<exception=OSError(65, 'No route to host')>
Traceback (most recent call last):
  File "/home/urybot/.pyenv/versions/3.4.1/lib/python3.4/asyncio/tasks.py", line 319, in _step
    result = coro.send(value)
  File "/home/urybot/.pyenv/versions/3.4.1/lib/python3.4/asyncio/base_events.py", line 424, in create_connection
    raise exceptions[0]
  File "/home/urybot/.pyenv/versions/3.4.1/lib/python3.4/asyncio/base_events.py", line 410, in create_connection
    yield from self.sock_connect(sock, address)
  File "/home/urybot/.pyenv/versions/3.4.1/lib/python3.4/asyncio/futures.py", line 350, in __iter__
    return self.result()  # May raise too.
  File "/home/urybot/.pyenv/versions/3.4.1/lib/python3.4/asyncio/futures.py", line 243, in result
    raise self._exception
  File "/home/urybot/.pyenv/versions/3.4.1/lib/python3.4/asyncio/selector_events.py", line 302, in _sock_connect
    sock.connect(address)
OSError: [Errno 65] No route to host
```

**Comment by alanbriolat** [comment]
I'd like to look into this, but can you figure out a way to reliably reproduce this error? I can cause "connect call failed" and "network unreachable", but I can't get anything that looks like this...

**Comment by alanbriolat** [comment]
I still haven't figured out how to synthesise various disconnects and failures to connect, however in theory the current bot loop should work as intended... Let me know if you get another one of these?

**Comment by LordAro** [comment]
Not seen this in quite some time, closing presumed fixed with later versions
